trigger:
  branches:
    include:
      - master
  paths:
    include:
      - app/* 
      - k8s/*
      - infra-pipelines/app-pipeline.yaml

pool:
  name: 'banco-pichincha'

variables:
  dockerRegistryServiceConnection: 'DockerHub-Connection' 
  imageName: 'brandon2399/devops-challenge'
  containerRegistry: 'docker.io'
  dockerfilePath: '$(Build.SourcesDirectory)/app/Dockerfile'
  tag: '$(Build.BuildId)'

  # Lo ideal es obtenerla dinámicamente
  k8sMasterIP: 13.218.91.114
  sshKeySecureFile: 'devops-key.pem'

stages:
- stage: CI
  displayName: Build and Push
  jobs:
  - job: Build
    displayName: Build
    steps:
    - script: |
        python3 -m pip install --upgrade pip
        pip3 install -r app/requirements.txt
        pip3 install pytest httpx
      displayName: 'Instalar Dependencias'

    - script: |
        # Ejecutar pruebas unitarias (Requisito TDD)
        # pytest # Descomenta esto cuando creemos los tests reales
        cd app
        python3 -m pytest
      displayName: 'Ejecutar Pruebas Unitarias (Pytest)'

    - task: Docker@2
      displayName: Build and Push to Docker Hub
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
          latest

- stage: CD
  displayName: Deploy to K8s
  dependsOn: CI
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  jobs:
  - job: Deploy
    displayName: Deploy via SSH
    steps:
    - task: DownloadSecureFile@1
      name: sshKey
      displayName: 'Descargar Llave PEM'
      inputs:
        secureFile: '$(sshKeySecureFile)'

    - script: |
        chmod 400 $(sshKey.secureFilePath)
        
        ssh -o StrictHostKeyChecking=no -i $(sshKey.secureFilePath) ubuntu@$(k8sMasterIP) "
          
          # 1. Configurar Kind
          cat <<EOF > kind-config.yaml
        kind: Cluster
        apiVersion: kind.x-k8s.io/v1alpha4
        nodes:
        - role: control-plane
          extraPortMappings:
          - containerPort: 30000
            hostPort: 30000
        - role: worker
        EOF

          # 2. Crear Cluster si no existe
          # Usamos 'kind' como nombre por defecto
          if ! sudo kind get clusters | grep -q 'kind'; then
            echo 'Creando cluster...'
            sudo kind create cluster --config kind-config.yaml
          fi

          # ### FIX IMPORTANTE: OBTENER LAS CREDENCIALES ###
          # 1. Crear carpeta .kube si no existe
          mkdir -p /home/ubuntu/.kube
          
          # 2. Extraer el kubeconfig del cluster (aunque sea de root) y guardarlo en el usuario ubuntu
          sudo kind get kubeconfig --name kind > /home/ubuntu/.kube/config
          
          # 3. Dar permisos al usuario ubuntu para leer ese archivo
          sudo chown ubuntu:ubuntu /home/ubuntu/.kube/config
          chmod 600 /home/ubuntu/.kube/config
          
          # 4. Decirle a kubectl dónde está el archivo
          export KUBECONFIG=/home/ubuntu/.kube/config
          # ##############################################

          # 3. Generar Manifiestos HPA agregado para Dynamic Grow
          echo 'Generando manifiestos...'
          cat <<EOF > app.yaml
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: devops-api
        spec:
          replicas: 2
          selector:
            matchLabels:
              app: devops-api
          template:
            metadata:
              labels:
                app: devops-api
            spec:
              containers:
              - name: devops-api
                image: $(imageName):$(Build.BuildId)
                imagePullPolicy: Always
                ports:
                - containerPort: 8000
                resources:
                  limits:
                    memory: '256Mi'
                    cpu: '500m'
                  requests:
                    memory: '128Mi'
                    cpu: '250m'
        ---
        apiVersion: v1
        kind: Service
        metadata:
          name: devops-api-service
        spec:
          type: NodePort
          selector:
            app: devops-api
          ports:
          - protocol: TCP
            port: 80
            targetPort: 8000
            nodePort: 30000
        ---
        apiVersion: autoscaling/v1
        kind: HorizontalPodAutoscaler
        metadata:
          name: devops-api-hpa
        spec:
          scaleTargetRef:
            apiVersion: apps/v1
            kind: Deployment
            name: devops-api
          minReplicas: 2
          maxReplicas: 5
          targetCPUUtilizationPercentage: 70
        EOF

          # 4. Desplegar
          echo 'Aplicando configuración en Kubernetes...'
          kubectl apply -f app.yaml
          
          echo 'Actualizando imagen...'
          kubectl set image deployment/devops-api devops-api=$(imageName):$(Build.BuildId)
          
          echo 'Esperando despliegue...'
          kubectl rollout status deployment/devops-api
          
          echo '¡ÉXITO!'
        "
      displayName: 'Desplegar en Kubernetes Remoto'