trigger:
  branches:
    include:
      - master
  paths:
    include:
      - infra/* 

pool:
  name: 'banco-pichincha'

variables:
  awsRegion: 'us-east-1'
  stackName: 'devops-assessment-stack'

steps:

# - task: AWSCLI@2 
#   displayName: 'Limpiar Stack en estado Rollback'
#   inputs:
#     awsCredentials: aws
#     regionName: '$(awsRegion)'
#     scriptType: 'bash'            
#     scriptLocation: 'inlineScript' 
#     inlineScript: |
#       STATUS=$(aws cloudformation describe-stacks --stack-name $(stackName) --query "Stacks[0].StackStatus" --output text 2>/dev/null || echo "NOT_FOUND")
#       echo "Estado actual del stack: $STATUS"
#       if [ "$STATUS" == "ROLLBACK_COMPLETE" ]; then
#         echo "Detectado stack muerto. Eliminando..."
#         aws cloudformation delete-stack --stack-name $(stackName)
#         aws cloudformation wait stack-delete-complete --stack-name $(stackName)
#         echo "Stack eliminado."
#       fi


- task: AmazonWebServices.aws-vsts-tools.CloudFormationCreateOrUpdateStack.CloudFormationCreateOrUpdateStack@1
  displayName: 'Desplegar Infraestructura con CloudFormation'
  inputs:
    awsCredentials: aws 
    regionName: '$(awsRegion)'
    stackName: '$(stackName)'
    templateSource: 'file'
    templateFile: 'infra/ec2-k8s-stack.yaml'
    templateParametersSource: 'inline'
    templateParameters: |
      [
        {
          "ParameterKey": "KeyName",
          "ParameterValue": "devops-key" 
        },
        {
          "ParameterKey": "InstanceType",
          "ParameterValue": "t2.micro"
        }
      ]
    