trigger:
  branches:
    include:
      - master
  paths:
    include:
      - infra/* 

pool:
  name: 'banco-pichincha'

variables:
  awsRegion: 'us-east-1'
  stackName: 'devops-assessment-stack'

steps:
- task: AmazonWebServices.aws-vsts-tools.CloudFormationCreateOrUpdateStack.CloudFormationCreateOrUpdateStack@1
  displayName: 'Desplegar Infraestructura con CloudFormation'
  inputs:
    awsCredentials: aws 
    regionName: '$(awsRegion)'
    stackName: '$(stackName)'
    templateSource: 'file'
    templateFile: 'infra/ec2-k8s-stack.yaml'
    templateParametersSource: 'inline'
    templateParameters: |
      [
        {
          "ParameterKey": "KeyName",
          "ParameterValue": "devops-key" 
        },
        {
          "ParameterKey": "InstanceType",
          "ParameterValue": "t2.micro"
        }
      ]
    